<div class="alert alert-info" markdown="1">

#### Homework 4, Problem 10 Supplemental Notebook

# Lines and Planes in $\mathbb{R}^3$

### Math 124: Vectors, Matrices, and Applications, Fall 2026

<small><a style="text-decoration: none" href="https://math124.org">math124.org</a></small>

</div>

### Instructions

Most homeworks and some labs will have a Jupyter Notebook, like this one, containing Python code that supplements our understanding of the relevant mathematical ideas of the week.

---

Open this notebook in Google Colab. Instructions on how to use Google Colab are at [math124.org/running-code](https://math124.org/running-code).

**Most importantly, make sure to click "Copy to Drive" and rename the notebook before proceeding!**

---

Together, the tasks in this notebook constitute your score for Homework 4, Problem 10, worth **7 points**. You won't need to submit this notebook anywhere. Instead, at the bottom, we'll tell you what to include in your PDF submission for Homework 4 that you upload to Pensive.

Work from top to bottom. **The only code you need to write is the function `reflection(v, w)`.** Replace the `...` in its cell. All other code is supplied: run it without editing it. If you change your function, run its cell again and rerun the cells below it so they use your new version.

## From projection to reflection

---

In Homework 1, you changed the **colors** of pixels in an image. This time, you'll change their **positions** to create a mirror image, while keeping the colors the same.

**Goal: Implement the reflection formula from Problem 9, then use your function to reflect an image across a line that you control.**

We'll start with a single vector. Once your function works, the supplied code will let you upload an image and reflect it across different lines. The image lives in $\mathbb{R}^2$, but your function will also work for vectors in $\mathbb{R}^3$, just as in Problem 9.

Let $\vec v$ be the vector we want to reflect, and let $\vec w$ be a **nonzero direction vector** for a line through the origin. In Python, `w` is the name of this direction vector; the line itself is $\ell=\operatorname{span}(\vec w)$.

The projection of $\vec v$ onto the line is

$$\vec p=\frac{\vec v\cdot\vec w}{\vec w\cdot\vec w}\vec w.$$

The vector $\vec v-\vec p$ is the part perpendicular to the line. Reflection keeps $\vec p$ and reverses that perpendicular part, giving

$$\vec v_{\mathrm{ref}}=\vec p-(\vec v-\vec p)=2\vec p-\vec v.$$

This matches the picture in Problem 9: the tip of $\vec p$ is halfway between the tips of $\vec v$ and its reflection.

**The direction vector does not need to have length 1.** For example, $\begin{bmatrix}1\\1\end{bmatrix}$ and $\begin{bmatrix}2\\2\end{bmatrix}$ describe the same line, so they must give the same reflection. The denominator in the projection formula accounts for this.

Run the cell below to import NumPy.

In [ ]:
import numpy as np

<div class="alert alert-warning" markdown="1">

### Task 1: Implement Reflection (5 pts)

</div>

Complete `reflection(v, w)`. It takes the vector `v` to reflect and the direction vector `w`, in that order, and returns the reflected vector as a NumPy array.

You may assume both inputs are one-dimensional NumPy arrays of the same length and that `w` is nonzero. Your function should work for any number of entries, including both the two-dimensional and three-dimensional examples below.

Recall that `np.dot(a, b)` computes a dot product, `*` multiplies an array by a scalar, and `-` subtracts arrays entry by entry. Use the arrays directly; you do not need to calculate the coordinates separately or write a loop. Do not round inside your function.

Example behavior is given below.

```python
>>> reflection(np.array([3, 4]), np.array([1, 0]))
array([ 3., -4.])

>>> reflection(np.array([7, -3]), np.array([1, 1]))
array([-3.,  7.])

>>> reflection(np.array([7, -3]), np.array([2, 2]))
array([-3.,  7.])

>>> reflection(np.array([1, 2, 3]), np.array([0, 0, 2]))
array([-1., -2.,  3.])
```

The first example reflects across the $x$-axis. The next two reflect across the same line, $y=x$, using different direction vectors. The last reflects across the $z$-axis in $\mathbb{R}^3$.

In [ ]:
def reflection(v, w):
    ...

Run the supplied checks below. If a check fails, revisit your function, rerun its cell, and try again. The checks use `np.allclose` to allow for tiny differences caused by the way computers store real numbers.

In [ ]:
#@title Check your reflection function { display-mode: "form" }
examples = [
    ([3, 4], [1, 0], [3, -4]),
    ([7, -3], [1, 1], [-3, 7]),
    ([7, -3], [2, 2], [-3, 7]),
    ([1, 2, 3], [0, 0, 2], [-1, -2, 3]),
    ([2, 4], [1, 2], [2, 4]),
    ([0, 0], [1, 2], [0, 0]),
]
for v_values, w_values, expected in examples:
    v = np.array(v_values, dtype=float)
    w = np.array(w_values, dtype=float)
    result = reflection(v.copy(), w.copy())
    assert isinstance(result, np.ndarray) and result.shape == v.shape, (
        'Your function must return a NumPy array with the same shape as v.'
    )
    assert np.allclose(result, expected), (
        f'For v = {v} and w = {w}, expected {expected}, but got {result}.'
    )
    print(f'{v_values} reflected across span({w_values}): {result}')
print('All example checks passed!')

**🚨 For Task 1, include a screenshot of your completed function and the successful check output in your PDF. 🚨**

<div class="alert alert-warning" markdown="1">

### Task 2: Reflect Your Image (2 pts)

</div>

Now we'll use your function to make a mirror image. **All the code from here on is supplied.**

### Upload an image

Run the cell below and use the **Choose Files** button to upload one PNG or JPG image from your computer. A picture with a recognizable left and right side, such as a short word or an asymmetric drawing, makes the reflection easy to see.

The supplied code resizes your image to **100 × 100 pixels**. We'll enlarge those pixels on the canvas so you can see them. The colors stay the same; reflection changes where they appear.

If you want to try a different image, rerun this upload cell and then the canvas cell below it.

In [ ]:
#@title Upload and resize your image { display-mode: "form" }
from google.colab import files
from PIL import Image, ImageOps
from IPython.display import display, HTML
import io

uploaded = files.upload()
if not uploaded:
    raise ValueError('Choose an image, then rerun this cell.')
filename = next(iter(uploaded))
with Image.open(io.BytesIO(uploaded[filename])) as image_file:
    image = ImageOps.exif_transpose(image_file).convert('RGBA')
new_width = 100
new_height = 100
small_image = image.resize((new_width, new_height), Image.Resampling.LANCZOS)
print(f'Using {filename}: {image.width} × {image.height} → {new_width} × {new_height} pixels.')
display(small_image.resize((new_width * 4, new_height * 4), Image.Resampling.NEAREST))

### An image is a collection of positions

Think of each pixel's position as the tip of a vector $\begin{bmatrix}x\\y\end{bmatrix}$. Here, $x$ increases to the right and $y$ increases upward. Reflecting the image means reflecting these position vectors while keeping their colors.

The slider chooses an angle $\theta$, measured **counterclockwise from the positive $x$-axis**. The supplied code uses the direction vector

$$\vec w=\begin{bmatrix}\cos\theta\\\sin\theta\end{bmatrix}.$$

At $0^\circ$, the line is horizontal. At $90^\circ$, it is vertical. At $180^\circ$, it is the same horizontal line as at $0^\circ$, with the direction vector pointing the opposite way.

Run the next cell, then drag the slider. The **dotted blue line** is the line of reflection and passes through the origin. The image labeled **Original** stays upright. As you turn the line, the supplied code moves that image so it stays entirely on one side of the line, with its reflection on the other side. This movement is just how we arrange the picture; your function performs the reflection.

The supplied code uses your function to reflect three corners of the image, then draws the pixels between those reflected corners. This works because reflection preserves straight lines and evenly spaced positions.

Try $0^\circ$, $90^\circ$, and a tilted line such as $45^\circ$. At $0^\circ$, you should see a top-to-bottom flip; at $90^\circ$, a left-to-right flip. For a tilted line, look for matching features the same distance from opposite sides of the line.

In [ ]:
#@title Explore your image reflection { display-mode: "form" }
import base64
import json
import uuid

# Prepare the image and all slider positions using YOUR reflection function.
# The browser only draws the results, so dragging the slider needs no Python callback.
width, height = small_image.size
radius = np.hypot(width, height) / 2
padding = max(4, radius * 0.20)
frames = []
for theta_degrees in range(181):
    theta = np.deg2rad(theta_degrees)
    w = np.array([np.cos(theta), np.sin(theta)])
    normal = np.array([-w[1], w[0]])
    center = (radius + padding) * normal
    # Top-left, top-right, and bottom-left corners in x-right, y-up coordinates.
    corners = center + np.array([
        [-width / 2, height / 2],
        [width / 2, height / 2],
        [-width / 2, -height / 2],
    ])
    reflected = np.array([reflection(corner.copy(), w.copy()) for corner in corners], dtype=float)
    if reflected.shape != (3, 2) or not np.isfinite(reflected).all():
        raise ValueError('Check your reflection function and rerun Task 1 before continuing.')
    frames.append(dict(w=w.tolist(), original=corners.tolist(), reflected=reflected.tolist()))

image_buffer = io.BytesIO()
small_image.save(image_buffer, format='PNG')
image_base64 = base64.b64encode(image_buffer.getvalue()).decode('ascii')
canvas_template = r"""<div id="__ID__" style="max-width:1000px;margin:12px auto;color:#202020;font:17px Palatino,Georgia,serif">
  <div style="padding:18px;border:1px solid #d6dce2;border-radius:10px;background:#fff">
    <label style="display:block" for="__ID__-theta">Angle θ: <strong data-angle>45°</strong></label>
    <input id="__ID__-theta" aria-label="Line angle in degrees" type="range" min="0" max="180" step="1" value="45" style="width:100%;margin:12px 0;accent-color:#2467a0">
    <div style="display:flex;justify-content:space-between;font-size:14px;color:#555"><span>0° · horizontal</span><span>90° · vertical</span><span>180° · horizontal</span></div>
    <div style="display:flex;justify-content:center;align-items:center;gap:8px;margin-top:14px">
      <span>Direction vector</span>
      <math xmlns="http://www.w3.org/1998/Math/MathML" display="inline" style="font-size:21px">
        <mrow>
          <mover accent="true"><mi>w</mi><mo>→</mo></mover><mo>=</mo>
          <mrow><mo stretchy="true">[</mo>
            <mtable columnalign="center" rowspacing="0.25em">
              <mtr><mtd><mn data-wx>0.707</mn></mtd></mtr>
              <mtr><mtd><mn data-wy>0.707</mn></mtd></mtr>
            </mtable>
          <mo stretchy="true">]</mo></mrow>
        </mrow>
      </math>
    </div>
    <canvas width="1000" height="440" role="img" aria-label="Original image and its reflection on opposite sides of a dotted blue line through the origin" style="display:block;width:100%;height:auto;margin-top:8px"></canvas>
    <p style="margin:8px 0 0;font-size:15px;line-height:1.45;text-align:center">The original stays upright and moves as the line turns.<br>The reflected image is drawn using your <code>reflection</code> function.</p>
  </div>
</div>
<script>
(() => {
  const root = document.getElementById('__ID__');
  const frames = __FRAMES__;
  const extent = __EXTENT__;
  const w = __WIDTH__, h = __HEIGHT__;
  const canvas = root.querySelector('canvas');
  const ctx = canvas.getContext('2d');
  const slider = root.querySelector('input');
  const picture = new Image();
  const scale = Math.min(canvas.width - 100, canvas.height - 110) / (2 * extent);
  const screen = ([x, y]) => [canvas.width / 2 + scale*x, canvas.height / 2 - scale*y];
  function segment(a, b, color, width, dash=[]) {
    const A = screen(a), B = screen(b);
    ctx.beginPath(); ctx.setLineDash(dash); ctx.strokeStyle = color; ctx.lineWidth = width;
    ctx.moveTo(...A); ctx.lineTo(...B); ctx.stroke(); ctx.setLineDash([]);
  }
  function drawImage(corners, label) {
    const [A, B, C] = corners.map(screen);
    ctx.save();
    ctx.transform((B[0]-A[0])/w, (B[1]-A[1])/w,
                  (C[0]-A[0])/h, (C[1]-A[1])/h, A[0], A[1]);
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(picture, 0, 0, w, h);
    ctx.restore();
    const D = [B[0]+C[0]-A[0], B[1]+C[1]-A[1]];
    ctx.strokeStyle = '#777'; ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(...A); ctx.lineTo(...B); ctx.lineTo(...D); ctx.lineTo(...C); ctx.closePath(); ctx.stroke();
    const centerX = (B[0]+C[0])/2;
    const bottom = Math.max(A[1],B[1],C[1],D[1]);
    ctx.font = '17px Palatino, Georgia, serif';
    ctx.textAlign = 'center'; ctx.textBaseline = 'top';
    const textWidth = ctx.measureText(label).width;
    ctx.fillStyle = 'rgba(255,255,255,0.94)'; ctx.fillRect(centerX-textWidth/2-5,bottom+5,textWidth+10,23);
    ctx.fillStyle = '#202020'; ctx.fillText(label, centerX, bottom+7);
  }
  function draw() {
    const theta = Number(slider.value), frame = frames[theta];
    root.querySelector('[data-angle]').textContent = theta + '°';
    const pretty = x => (Math.abs(x)<0.0005 ? 0 : x).toFixed(3);
    root.querySelector('[data-wx]').textContent = pretty(frame.w[0]);
    root.querySelector('[data-wy]').textContent = pretty(frame.w[1]);
    ctx.clearRect(0,0,canvas.width,canvas.height);
    ctx.fillStyle='#fff'; ctx.fillRect(0,0,canvas.width,canvas.height);
    segment([-extent,0],[extent,0],'#ddd',1);
    segment([0,-extent],[0,extent],'#ddd',1);
    ctx.font='15px Palatino, Georgia, serif'; ctx.fillStyle='#777'; ctx.textAlign='left'; ctx.textBaseline='middle';
    const X=screen([extent,0]), Y=screen([0,extent]);
    ctx.fillText('x',X[0]+9,X[1]); ctx.fillText('y',Y[0]+8,Y[1]);
    const end = frame.w.map(x=>extent*x);
    segment(end.map(x=>-x),end,'#2467a0',2.5,[3,6]);
    const O=screen([0,0]); ctx.beginPath(); ctx.arc(...O,3,0,2*Math.PI); ctx.fillStyle='#2467a0'; ctx.fill();
    ctx.fillStyle='#555'; ctx.fillText('0',O[0]+8,O[1]+13);
    drawImage(frame.original,'Original');
    drawImage(frame.reflected,'Reflected');
  }
  slider.addEventListener('input',draw);
  picture.onload=draw;
  picture.src='data:image/png;base64,__IMAGE__';
})();
</script>
"""
canvas_html = (canvas_template
    .replace('__ID__', 'reflection-' + uuid.uuid4().hex)
    .replace('__FRAMES__', json.dumps(frames, separators=(',', ':')))
    .replace('__EXTENT__', str(2 * radius + padding))
    .replace('__WIDTH__', str(width))
    .replace('__HEIGHT__', str(height))
    .replace('__IMAGE__', image_base64))
display(HTML(canvas_html))

**🚨 For Task 2, include one screenshot of your canvas with a tilted line in your PDF. Make sure the angle, original image, and reflected image are visible. No written response is required. 🚨**

## Finish line 🏁

For Homework 4, **Problem 10** on Pensive, include the following in your PDF. These tasks are worth **7 points total**.

1. **Task 1 (5 pts):** A screenshot of your completed `reflection(v, w)` function and the successful check output.
2. **Task 2 (2 pts):** One screenshot of your canvas with a tilted line, showing the angle, original image, and reflected image.

You do not need to submit this notebook anywhere.